### ISSUE TITLE
about dataset and dataloader

### ISSUE THREAD

**Issue by NewEricWang** [jyhan03/channel-decorrelation#1]
Hi,
    How to generate the files "ref_scp" and "aux_scp"?  What formats?
    How to generate the file "wsj0_2mix_extr_tr.spk"? 

Thanks

**Comment by jyhan03** [comment]
Hi,
scp formats:   wav_name    /path/wav_name.wav   
e.g. 050a0501_1.7783_442o030z_-1.7783.wav   /path/050a0501_1.7783_442o030z_-1.7783.wav

I generate the scp files using "awk" command in shell, you can use python as well.

For the "wsj0_2mix_extr_tr.spk", I don't have its simulation code. I just using it...   
But we also released a similar simulation code, please see:
https://github.com/jyhan03/icassp22-dataset/blob/main/scripts/get_aux_aishell.py

Best

**Comment by NewEricWang** [comment]
Thanks for your quick replay!
What is stored in the file “ref_scp”? target speaker's reverberate speech?
What is stored in the file “aux_scp”? target speaker's anechoic speech?
What is stored in the file "wsj0_2mix_extr_tr.spk"? What is its format?  I can't find it in the project. 

Thanks!

**Comment by NewEricWang** [comment]
I think I can generate the file "ref_scp" and "aux_scp" correctly. 
"ref_scp" store target speaker's anechoic speech file list in the directory "./data/anechoic/simulation/mmm/2speakers/wav8k/min/tr/s1/";
"aux_scp" store file list of another speech corresponding to the same target speaker in the directory "./data/anechoic/simulation/mmm/2speakers/wav8k/min/tr/aux/" .

Now only problem is where I can find the file "wsj0_2mix_extr_tr.spk"?

**Comment by jyhan03** [comment]
Hi, please see:
https://github.com/xuchenglin28/speaker_extraction/tree/master/simulation
